function A = A_fn_le(Ig,d1,d2,m,phi1,phi2,theta)
%A_fn_le
%    A = A_fn_le(Ig,D1,D2,M,PHI1,PHI2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 10:34:37

A = reshape([m,0.0,0.0,-cos(phi1).*sin(theta)-cos(theta).*sin(phi1),-cos(phi2).*sin(theta)-cos(theta).*sin(phi2),0.0,m,0.0,cos(phi1).*cos(theta)-sin(phi1).*sin(theta),cos(phi2).*cos(theta)-sin(phi2).*sin(theta),0.0,0.0,Ig,-d1.*cos(theta).*(cos(phi1).*cos(theta)-sin(phi1).*sin(theta))-d1.*sin(theta).*(cos(phi1).*sin(theta)+cos(theta).*sin(phi1)),d2.*cos(theta).*(cos(phi2).*cos(theta)-sin(phi2).*sin(theta))+d2.*sin(theta).*(cos(phi2).*sin(theta)+cos(theta).*sin(phi2)),sin(phi1+theta),-cos(phi1+theta),-d1,0.0,0.0,sin(phi2+theta),-cos(phi2+theta),-d2,0.0,0.0],[5,5]);
end
