function A = A_fn(I,d1,d2,m,phi1,phi2,theta)
%A_fn
%    A = A_fn(I,D1,D2,M,PHI1,PHI2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 10:35:14

t2 = cos(phi1);
t3 = cos(phi2);
t4 = cos(theta);
t5 = sin(phi1);
t6 = sin(phi2);
t7 = sin(theta);
t8 = t2.*t4;
t9 = t3.*t4;
t10 = t2.*t7;
t11 = t4.*t5;
t12 = t3.*t7;
t13 = t4.*t6;
t14 = t5.*t7;
t15 = t6.*t7;
t16 = -t14;
t17 = -t15;
t18 = t10+t11;
t19 = t12+t13;
t20 = t8+t16;
t21 = t9+t17;
t22 = d1.*t7.*t18;
t23 = d1.*t4.*t20;
A = reshape([m,0.0,0.0,-t18,-t19,0.0,m,0.0,t20,t21,0.0,0.0,I,-t22-t23,d2.*t4.*t21+d2.*t7.*t19,t18,-t8+t14,t22+t23,0.0,0.0,t19,-t9+t15,-d1.*t4.*t21-d1.*t7.*t19,0.0,0.0],[5,5]);
end
