function b = b_fn_le(d1,d2,phi1,phi2,theta,thetadot,xdot,ydot)
%B_FN_LE
%    B = B_FN_LE(D1,D2,PHI1,PHI2,THETA,THETADOT,XDOT,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 10:34:37

b = [0.0;0.0;0.0;thetadot.*((cos(phi1).*sin(theta)+cos(theta).*sin(phi1)).*(ydot-d1.*thetadot.*cos(theta))+(cos(phi1).*cos(theta)-sin(phi1).*sin(theta)).*(xdot+d1.*thetadot.*sin(theta))+d1.*thetadot.*cos(theta).*(cos(phi1).*sin(theta)+cos(theta).*sin(phi1))-d1.*thetadot.*sin(theta).*(cos(phi1).*cos(theta)-sin(phi1).*sin(theta)));thetadot.*((cos(phi2).*sin(theta)+cos(theta).*sin(phi2)).*(ydot+d2.*thetadot.*cos(theta))+(cos(phi2).*cos(theta)-sin(phi2).*sin(theta)).*(xdot-d2.*thetadot.*sin(theta))-d2.*thetadot.*cos(theta).*(cos(phi2).*sin(theta)+cos(theta).*sin(phi2))+d2.*thetadot.*sin(theta).*(cos(phi2).*cos(theta)-sin(phi2).*sin(theta)))];
end
