function b = b_fn(d1,d2,phi1,phi2,theta,thetadot,xgdot,ygdot)
%B_FN
%    B = B_FN(D1,D2,PHI1,PHI2,THETA,THETADOT,XGDOT,YGDOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 10:35:15

t2 = cos(phi1);
t3 = cos(phi2);
t4 = cos(theta);
t5 = sin(phi1);
t6 = sin(phi2);
t7 = sin(theta);
t8 = t2.*t4;
t9 = t3.*t4;
t10 = t2.*t7;
t11 = t4.*t5;
t12 = t3.*t7;
t13 = t4.*t6;
t14 = t5.*t7;
t15 = t6.*t7;
t16 = -t14;
t17 = -t15;
t18 = t10+t11;
t19 = t12+t13;
t20 = t8+t16;
t21 = t9+t17;
b = [0.0;0.0;0.0;thetadot.*(t20.*(xgdot+d1.*t7.*thetadot)+t18.*(ygdot-d1.*t4.*thetadot)+d1.*t4.*t18.*thetadot-d1.*t7.*t20.*thetadot);thetadot.*(t21.*(xgdot-d2.*t7.*thetadot)+t19.*(ygdot+d2.*t4.*thetadot)-d2.*t4.*t19.*thetadot+d2.*t7.*t21.*thetadot)];
end
