function A = A_matrix(m,x,y)
%A_matrix
%    A = A_matrix(M,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    20-Mar-2025 16:12:10

t2 = abs(x);
t3 = abs(y);
t6 = -m;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4+t5;
t8 = 1.0./sqrt(t7);
A = reshape([t6,0.0,x.*2.0,0.0,t6,y.*2.0,-t8.*x,-t8.*y,0.0],[3,3]);
end
