function b = B_matrix(g,m,xdot,ydot)
%B_matrix
%    B = B_matrix(G,M,XDOT,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    20-Mar-2025 16:12:10

b = [0.0;g.*m;xdot.^2.*-2.0-ydot.^2.*2.0];
end
