function A = A_matrix(m,x1,x2,y1,y2)
%A_matrix
%    A = A_matrix(M,X1,X2,Y1,Y2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    20-Mar-2025 15:36:54

A = reshape([-m,0.0,0.0,0.0,x1.*2.0-x2.*2.0,0.0,-m,0.0,0.0,y1.*2.0-y2.*2.0,0.0,0.0,-m,0.0,x1.*-2.0+x2.*2.0,0.0,0.0,0.0,-m,y1.*-2.0+y2.*2.0,-1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2).*(x1-x2),-1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2).*(y1-y2),1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2).*(x1-x2),1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2).*(y1-y2),0.0],[5,5]);
end
