function b = B_matrix(x1dot,x2dot,y1dot,y2dot)
%B_matrix
%    B = B_matrix(X1DOT,X2DOT,Y1DOT,Y2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    20-Mar-2025 15:36:54

b = [0.0;0.0;0.0;0.0;-x1dot.*(x1dot.*2.0-x2dot.*2.0)+x2dot.*(x1dot.*2.0-x2dot.*2.0)-y1dot.*(y1dot.*2.0-y2dot.*2.0)+y2dot.*(y1dot.*2.0-y2dot.*2.0)];
end
