function A = A_matrix(m1,m2)
%A_matrix
%    A = A_matrix(M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Mar-2025 14:23:29

A = reshape([-m1,0.0,-1.0,0.0,-m2,1.0,1.0,-1.0,0.0],[3,3]);
end
