function phidot = myphidot(t)
%MYPHIDOT
%    PHIDOT = MYPHIDOT(T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    31-Mar-2025 15:20:07

phidot = -(pi.*cos(pi.*(cos(t)-1.0)).^2.*sin(t)+pi.*sin(pi.*(cos(t)-1.0)).^2.*sin(t)+pi.*cos(pi.*(cos(t)-1.0)).*sin(t).*2.0)./(cos(pi.*(cos(t)-1.0)).*2.0-sin(pi.*(cos(t)-1.0))+6.0);
end
