function b = b_matrix(d1,d2,d3,g,l1,l2,m1,m2,m3,theta1,theta2,theta3,theta1dot,theta2dot,theta3dot)
%B_MATRIX
%    B = B_MATRIX(D1,D2,D3,G,L1,L2,M1,M2,M3,THETA1,THETA2,THETA3,THETA1DOT,THETA2DOT,THETA3DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-May-2025 14:25:39

b = [0.0;-g.*m1;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;-d1.*theta1dot.^2.*sin(theta1);d1.*theta1dot.^2.*cos(theta1);-d2.*theta2dot.^2.*sin(theta2)-l1.*theta1dot.^2.*sin(theta1);d2.*theta2dot.^2.*cos(theta2)+l1.*theta1dot.^2.*cos(theta1);-d3.*theta3dot.^2.*sin(theta3)-l1.*theta1dot.^2.*sin(theta1)-l2.*theta2dot.^2.*sin(theta2);d3.*theta3dot.^2.*cos(theta3)+l1.*theta1dot.^2.*cos(theta1)+l2.*theta2dot.^2.*cos(theta2)];
end
