function A = A_matrix(Ig,d,m,theta)
%A_matrix
%    A = A_matrix(Ig,D,M,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    31-Mar-2025 18:59:39

A = reshape([1.0,0.0,-m,0.0,-d.*m.*cos(theta),0.0,1.0,0.0,-m,-d.*m.*sin(theta),0.0,0.0,d.*m.*cos(theta),d.*m.*sin(theta),Ig+d.^2.*m.*cos(theta).^2+d.^2.*m.*sin(theta).^2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0],[5,5]);
end
