function b = B_matrix(d,g,m,omega,r,t,theta,thetadot)
%B_matrix
%    B = B_matrix(D,G,M,OMEGA,R,T,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    31-Mar-2025 18:59:40

t2 = sin(theta);
t3 = thetadot.^2;
b = [0.0;-omega.^2.*r.*sin(omega.*t);d.*m.*t2.*t3;g.*m-d.*m.*t3.*cos(theta);d.*g.*m.*t2];
end
