function b = b_matrix(d1,d2,g,l1,m1,m2,theta1,theta2,theta1dot,theta2dot)
%B_MATRIX
%    B = B_MATRIX(D1,D2,G,L1,M1,M2,THETA1,THETA2,THETA1DOT,THETA2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 09:07:57

b = [0.0;-g.*m1;0.0;-g.*m2;0.0;0.0;-d1.*theta1dot.^2.*sin(theta1);d1.*theta1dot.^2.*cos(theta1);-d2.*theta2dot.^2.*sin(theta2)-l1.*theta1dot.^2.*sin(theta1);d2.*theta2dot.^2.*cos(theta2)+l1.*theta1dot.^2.*cos(theta1)];
end
