function theta2ddot = theta2ddot_fn(Ig2,d2,g,m2,theta2)
%THETA2DDOT_FN
%    THETA2DDOT = THETA2DDOT_FN(Ig2,D2,G,M2,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    01-Apr-2025 14:32:40

theta2ddot = -(d2.*g.*m2.*sin(theta2))./(Ig2+d2.^2.*m2);
end
