function wdots = wdots_fn(I1,I2,I3,w1,w2,w3)
%WDOTS_FN
%    WDOTS = WDOTS_FN(I1,I2,I3,W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-May-2025 14:09:51

wdots = [(I2.*w2.*w3-I3.*w2.*w3)./I1;-(I1.*w1.*w3-I3.*w1.*w3)./I2;(I1.*w1.*w2-I2.*w1.*w2)./I3];
end
